### ISSUE TITLE
Linksoffene Intervalle standardmäßig auf 1/2 y begrenzen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-macrogen#1]
Wenn es z.B. zu einem Knoten lediglich heißt: `notAfter 1827-03-18`, dann soll das behandelt werden wie zugleich `notBefore 1826-09-18` (idealerweise auch bei den inferierten).

**Comment by gerritbruening** [comment]
> 

nein | nicht nach | 1799-12-28 | heuristic |   | macrogenesis/handschriftendatierung_pre1800.xml:165
-- | -- | -- | -- | -- | --

wird als verwirrend empfunden, da man nicht gleich versteht, wo das herkommt (macrogenesis/handschriftendatierung_pre1800.xml:165)

**Comment by gerritbruening** [comment]
Und die rechtsoffenen auf 22. März 1832 begrenzen.

**Comment by gerritbruening** [comment]
Ich wusste mit "heuristic" erst was anzufangen, als ABR mich danach fragte. Könnte man nicht was sprechenderes hinschreiben wie "6m earlier than notBefore" oder dieses Datum sogar gar nicht erscheinen lassen, sondern nur für die Sortierung nutzen und dann wegwerfen?

**Comment by thvitt** [comment]
Die Visualisierungen sollten schon die informationen beinhalten, die die Grundlage für die Sortierung etc. bildet, sonst ist ja völlig unklar, wo die Datierung herkommen soll.

Für die ganzen Labels à la faust://self etc. müssen wir noch sprechende Bezeichnungen einführen. '6 Monate vor/nach anderer Grenze' oder so ist vielleicht was für’s Kommentarfeld der entsprechenden Kante?

**Comment by gerritbruening** [comment]
> wo die Datierung 

wo die Sortierung?
