### ISSUE TITLE
Render wa_... as WA ...

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-macrogen#16]

**Comment by gerritbruening** [comment]
OK, dann funktioniert die Referenz auf http://faustedition.net/bibliography#wa_I_15_2 nicht; der Eintrag ist aber da.

**Comment by thvitt** [comment]
ah, I see. The macrognesis files use faust://bibliography/wa_i_15_2 but the bibliography entry is wa_I_15_2 (large I)
