### ISSUE TITLE
Mention inscriptions in macrogenesis/{witness0

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-macrogen#3]
For example, here
http://dev.faustedition.net/macrogenesis/2_II_H.5
the two inscriptions are not mentioned. Is that intended?

**Comment by thvitt** [comment]
there are probably no links in the data … can we infer a temporal relationship between an inscription and its main witness? _i_ –temp-pre→ _w_? Or should there just be a nondescript link like for the temp-syn relation?

**Comment by gerritbruening** [comment]
> temporal relationship between an inscription and its main witness?

It is more a "part of" relationship. So an unused link that is not part of the chronology graph would be best.
