### ISSUE TITLE
Ignore datings as incorrect

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-macrogen#4]
For example,

> H P91: Pniower-Datierung wegen Signatur auszuschließen (Bo 205)

It would be good to add an attribute or something to deprecate and thus improve the resulting graph.

**Comment by thvitt** [comment]
use attribute `ignore="yes"` on the date/relation element.

I’ve updated the schema, but not implemented ignoring yet.

**Comment by gerritbruening** [comment]
Thanks, done!

**Comment by gerritbruening** [comment]
Great, thanks!
