### ISSUE TITLE
Labeling things

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-macrogen#7]
#### Kantenbeschriftungen, ggf. kann ein Kommentar (taucht in der Tabelle auf) hinzugefügt werden:

URL etc. | Beschriftung | Extra-Kommentar | (Erläuterung)
-- | -- | -- | --
faust://self | Faustedition |   | eigene Erkenntnis, Bestätigung vorh. Aussagen
faust://model/inscription | Inskription von  |   | u ist Inskription von v
faust://orphan/adoption | Inskription von, Datierungsanhalt für |   | u ist Inskription von v; v ist nicht anders in den Graphen eingebunden als durch u
faust://heuristic | künstliche Datierung | 6 Monate vor/nach $d | Künstliche Kante aufgrund einer

#### Überschriften auf http://dev.faustedition.net/macrogenesis  / Einheitliche Nomenklatur für Dinge

* Oberbegriff für Hs, Drucke, Inskriptionen
* Überbegriff für Hs, Drucke; aber nicht Inskriptionen

**Comment by gerritbruening** [comment]
OK, habe die Tabelle befüllt. 
Bei `faust://heuristic` wäre es zu wünschen, man könnte dies als Eigenschaft des Datumsknoten modellieren.
"Zeugen" als Oberbegriff finde ich pragmatisch OK, weil Inskriptionen (was tatsächlich der Oberbegriff ist; wir datieren immer Inskriptionen) nicht geläufig genug ist.

**Comment by thvitt** [comment]
Da muss man ggf. mittelfristig mal über interne Benennungen nachdenken, da im Datenmodell ja ein Unterschied zwischen Inskriptionen, wie sie aus faust://inscription/… entstehen, und Referenzen, die auf ein Dokument verweisen, besteht.

**Comment by thvitt** [comment]
Das mag ja alles in der Theorie sein, aber nicht im konkreten Datenmodell der aktuellen Implementierung. Und im Rest der Edition sind alles Dokumente/Zeugen

**Comment by gerritbruening** [comment]
Sehe ich ein. Dann hätte ich nix gegen einen Button "Zeugen und Inskriptionen".
