### ISSUE TITLE
orphan adoption in  IV H.1, IV H.12

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-macrogen#8]
>> IV H 1:
>> was bedeuten die roten Kreise mit orphan adoption?

> Verstehe ich jetzt gerade auch nicht.

Betrifft genauso IV H.12.

**Comment by gerritbruening** [comment]
Findet ABR verwirrend.

**Comment by thvitt** [comment]
ich verstehe nicht was du von mir willst

**Comment by gerritbruening** [comment]
Wir verstehen das nicht so richtig, insgesamt:
![grafik](https://user-images.githubusercontent.com/10358005/46541911-7c06e180-c8bd-11e8-887e-e087f5c911ec.png)

**Comment by thvitt** [comment]
Das ist aber nicht IV H.12. 


Die Grundidee der orphan-Kanten (schon länger implementiert) ist: Wenn _w_ ein Zeuge ist, der nirgends in den Makrogenese-XML-Daten erwähnt wird, aber eine Inskription _i(w)_ existiert, oder eine ambige Referenz _a_, die u.A. auf _w_ bezogen werden kann, dann wird eine Kante _i(w) → w_ bzw. _a → w_ eingezogen.

Danach haben wir andere Heuristiken für Inskriptionen und Ambiguitäten aufgeführt, die die meisten oder alle hiervon überflüssig machen sollten. Die Reihenfolge war ungünstig, ich habe das jetzt mal optimiert.
